version: 2

jobs:
  build:
    machine:
      enabled: true
    steps:
      - echo "BUILD"

  deploy:
    machine:
      enabled: true
    branches:
      only:
        - master
    steps:
      - echo "DEPLOY"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy
