version: 2

jobs:
  build:
    machine:
      enabled: true
    branches:
      only:
        - master
    steps:
      - checkout
      - run: |
          make release DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS TAG=`echo $TRAVIS_COMMIT | cut -c -7`
          make deploy DEPLOY_TOKEN=$DEPLOY_TOKEN TAG=`echo $TRAVIS_COMMIT | cut -c -7`
