version: 2

jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run: |
          echo "BUILD"
          make build TAG=`echo $CIRCLE_SHA1 | cut -c -7`

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run: |
          echo "DEPLOY 111"
          make release DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS TAG=`echo $CIRCLE_SHA1 | cut -c -7`

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
