// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Product
	User
	Token
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Описывает идентифицированный в каталоге товар
type Product struct {
	// Идентификатор Товара
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Наименование товара
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	// описание товара
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *Product) Reset()                    { *m = Product{} }
func (m *Product) String() string            { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()               {}
func (*Product) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type User struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Pass   string `protobuf:"bytes,2,opt,name=pass" json:"pass,omitempty"`
	Active bool   `protobuf:"varint,3,opt,name=active" json:"active,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

func (m *User) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type Token struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Token) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Token) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "api.Product")
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*Token)(nil), "api.Token")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x0a,
	0xe4, 0x62, 0x0f, 0x28, 0xca, 0x4f, 0x29, 0x4d, 0x2e, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe1, 0x62, 0x2d, 0xc9, 0x2c,
	0xc9, 0x49, 0x95, 0x60, 0x02, 0x0b, 0x41, 0x38, 0x42, 0x0a, 0x5c, 0xdc, 0x29, 0xa9, 0xc5, 0xc9,
	0x45, 0x99, 0x05, 0x25, 0x99, 0xf9, 0x79, 0x12, 0xcc, 0x60, 0x39, 0x64, 0x21, 0x25, 0x27, 0x2e,
	0x96, 0xd0, 0xe2, 0xd4, 0x22, 0x0c, 0xf3, 0x84, 0xb8, 0x58, 0x0a, 0x12, 0x8b, 0x8b, 0xa1, 0xc6,
	0x81, 0xd9, 0x42, 0x62, 0x5c, 0x6c, 0x89, 0xc9, 0x25, 0x99, 0x65, 0xa9, 0x60, 0x83, 0x38, 0x82,
	0xa0, 0x3c, 0x25, 0x5d, 0x2e, 0xd6, 0x90, 0xfc, 0xec, 0xd4, 0x3c, 0x6c, 0x8e, 0x2a, 0x4b, 0xcc,
	0x29, 0x85, 0x3b, 0x0a, 0xcc, 0x49, 0x62, 0x03, 0xfb, 0xc8, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x07, 0xba, 0x58, 0xf0, 0xe2, 0x00, 0x00, 0x00,
}
